import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import io.restassured.RestAssured;
import io.restassured.http.ContentType;
import io.restassured.response.Response;
import java.util.Map;

/**
 * AI-Generated Test for GET /users
 * Generated by Bob AI-Powered Test Oracle
 */
public class TestGetUsersTest {

    @Test
    public void test_get_users() {
        // Execute API call
        Response response = RestAssured.given()
            .contentType(ContentType.JSON)
            .when()
            .get("/users")
            .then()
            .statusCode(200)
            .extract()
            .response();

        Map<String, Object> responseBody = response.jsonPath().getMap("$");

        // AI-Generated Assertions
        // ID must be present and non-null
        assertNotNull(response.get("id"), "id should not be null");

        // ID should be unique across records
        assertNotNull(response.get("id"));

        // If numeric, must be positive (> 0)
        assertNotNull(response.get("id"));

        // Verify field is of type String
        assertNotNull(response.get("username"));

        // Verify field exists in response
        assertNotNull(response.get("username"));

        // Check if field should be nullable
        assertNotNull(response.get("username"), "username should not be null");

        // Validate RFC 5322 email format with regex
        assertNotNull(response.get("email"));

        // Email must not be null or empty
        assertFalse(response.get("email").toString().isEmpty(), "email should not be empty");

        // Verify valid domain with TLD
        assertNotNull(response.get("email"));

        // Maximum 254 characters per RFC 5321
        assertNotNull(response.get("email"));
    }
}
