"""
AI-Generated Test for GET /users
Generated by Bob AI-Powered Test Oracle
"""

import pytest
import requests
import re
from typing import Dict, Any


def test_get_users():
    """Test GET /users with AI-generated assertions"""
    # Execute API call
    response = requests.get(
        "http://localhost:8080/users",
        headers={"Content-Type": "application/json"}
    )
    
    # Verify status code
    assert response.status_code == 200, f"Expected status 200, got {response.status_code}"
    
    # Parse response
    response_data = response.json()
    
    # AI-Generated Assertions
    # ID must be present and non-null
    assert response['id'] is not None, "id should not be null" 

    # ID should be unique across records
    # Note: Uniqueness validation requires database or collection check
    assert response['id'] is not None

    # If numeric, must be positive (> 0)
    assert response['id'] > 0, "id should be positive" 

    # Verify field is of type String
    assert response['username'] is not None

    # Verify field exists in response
    assert 'username' in response, "username should be present in response" 

    # Check if field should be nullable
    assert response['username'] is not None, "username should not be null" 

    # Validate RFC 5322 email format with regex
    import re
    assert re.match(r'^[A-Za-z0-9+_.-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$', str(response['email'])), \
        "email should match expected format" 

    # Email must not be null or empty
    assert len(response['email']) > 0, "email should not be empty" 

    # Verify valid domain with TLD
    assert response['email'] is not None, "email validation" 

    # Maximum 254 characters per RFC 5321
    assert len(str(response['email'])) <= 254, \
        "email should not exceed maximum length"  # TODO: Define actual max length

    # Verify field is of type String
    assert response['firstName'] is not None

    # Verify field exists in response
    assert 'firstName' in response, "firstName should be present in response" 

    # Check if field should be nullable
    assert response['firstName'] is not None, "firstName should not be null" 

    # Verify field is of type String
    assert response['lastName'] is not None

    # Verify field exists in response
    assert 'lastName' in response, "lastName should be present in response" 

    # Check if field should be nullable
    assert response['lastName'] is not None, "lastName should not be null" 

    # Must be valid ISO 8601 timestamp
    import re
    assert re.match(r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}', str(response['createdAt'])), \
        "createdAt should match expected format" 

    # Creation timestamp required
    assert response['createdAt'] is not None, "createdAt should not be null" 

    # Cannot be in the future
    assert response['createdAt'] is not None, "createdAt validation" 

    # Must be valid ISO 8601 timestamp
    import re
    assert re.match(r'^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}', str(response['updatedAt'])), \
        "updatedAt should match expected format" 

    # Must be >= created_at
    assert response['updatedAt'] is not None, "updatedAt validation" 

    # Should be recent for active records
    assert response['updatedAt'] is not None, "updatedAt validation" 

    # Verify field is of type String
    assert response['role'] is not None

    # Verify field exists in response
    assert 'role' in response, "role should be present in response" 

    # Check if field should be nullable
    assert response['role'] is not None, "role should not be null" 


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
